# Generated by Django 6.0.3 on 2026-03-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='albums.album'),
        ),
    ]
